# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://hao1993.github.io
date_format: "ordinal"
title: hao's blog
subtitle: "记录成长"
description: "杨世浩的个人博客"
keywords: hao, ShiHao Yang
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 2

# ---------------- #
#      Author      #
# ---------------- #
author: ShiHao Yang
github_username: hao1993
location: BeiJing, China
email: ysh69550@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: hao1993/hao1993.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: hao1993
    repo: hao1993.github.io
    clientID: df4ac47f176c07e699d2
    clientSecret: b888907664cbf586ba97eb5607438910a5db1f95

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# Baidu Analytics
ba_track_id: 11d3aa996a63a709534916c078d5ba1a


