# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://hao1993.github.io
date_format: "ordinal"
title: hao's blog
subtitle: "记录成长，记录生活"
description: "杨世浩的个人博客"
keywords: hao, ShiHao Yang
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 2

# ---------------- #
#      Author      #
# ---------------- #
author: ShiHao Yang
github_username: hao1993
location: BeiJing, China
email: ysh69550@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: hao1993/hao1993.github.io

